spring:
  application:
    name: exercise
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:katadb}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:kata}
    password: ${DB_PASSWORD:pwd}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

